// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLT4jrPfSxXks8_fIdUbTzsN0fXsOgFPQ',
    appId: '1:247751894047:web:d7ab2f28bf4b266002a12a',
    messagingSenderId: '247751894047',
    projectId: 'leisure-app-eac43',
    authDomain: 'leisure-app-eac43.firebaseapp.com',
    storageBucket: 'leisure-app-eac43.firebasestorage.app',
    measurementId: 'G-3MH490F1EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoy8AW7mFKd7azHQfbVNs0PHb-DnmAnYw',
    appId: '1:247751894047:android:f2f55b741e1fe4f202a12a',
    messagingSenderId: '247751894047',
    projectId: 'leisure-app-eac43',
    storageBucket: 'leisure-app-eac43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9tzgfrGIwwqdSArtxjLtqGg8LqIUsrwQ',
    appId: '1:247751894047:ios:654caba5d3203ec502a12a',
    messagingSenderId: '247751894047',
    projectId: 'leisure-app-eac43',
    storageBucket: 'leisure-app-eac43.firebasestorage.app',
    iosBundleId: 'com.example.leisureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9tzgfrGIwwqdSArtxjLtqGg8LqIUsrwQ',
    appId: '1:247751894047:ios:654caba5d3203ec502a12a',
    messagingSenderId: '247751894047',
    projectId: 'leisure-app-eac43',
    storageBucket: 'leisure-app-eac43.firebasestorage.app',
    iosBundleId: 'com.example.leisureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLT4jrPfSxXks8_fIdUbTzsN0fXsOgFPQ',
    appId: '1:247751894047:web:345a78808168fcfe02a12a',
    messagingSenderId: '247751894047',
    projectId: 'leisure-app-eac43',
    authDomain: 'leisure-app-eac43.firebaseapp.com',
    storageBucket: 'leisure-app-eac43.firebasestorage.app',
    measurementId: 'G-NYETQ2YVGV',
  );
}
